local M = {}

---@param c vitesse.Palette
---@param opts vitesse.Config
function M.get(c, opts)
  local hl = {}

  local function hi(name, val)
    hl[name] = val
  end

  -- Terminal colors
  if opts.terminal_colors then
    vim.g.terminal_color_0 = c.terminal.black
    vim.g.terminal_color_1 = c.terminal.red
    vim.g.terminal_color_2 = c.terminal.green
    vim.g.terminal_color_3 = c.terminal.yellow
    vim.g.terminal_color_4 = c.terminal.blue
    vim.g.terminal_color_5 = c.terminal.magenta
    vim.g.terminal_color_6 = c.terminal.cyan
    vim.g.terminal_color_7 = c.terminal.white
    vim.g.terminal_color_8 = c.terminal.black_bright
    vim.g.terminal_color_9 = c.terminal.red_bright
    vim.g.terminal_color_10 = c.terminal.green_bright
    vim.g.terminal_color_11 = c.terminal.yellow_bright
    vim.g.terminal_color_12 = c.terminal.blue_bright
    vim.g.terminal_color_13 = c.terminal.magenta_bright
    vim.g.terminal_color_14 = c.terminal.cyan_bright
    vim.g.terminal_color_15 = c.terminal.white_bright
  end

  -- Editor
  hi("ColorColumn", { bg = c.bg_highlight })
  hi("Conceal", { fg = c.fg_gutter })
  hi("CurSearch", { fg = c.bg, bg = c.yellow, bold = true })
  hi("Cursor", { fg = c.bg, bg = c.fg })
  hi("CursorColumn", { bg = c.bg_highlight })
  hi("CursorIM", { fg = c.bg, bg = c.fg })
  hi("CursorLine", { bg = c.bg_highlight })
  hi("CursorLineNr", { fg = c.fg_dark, bold = true })
  hi("CursorLineSign", { bg = c.bg_highlight })
  hi("CursorLineFold", { bg = c.bg_highlight })
  hi("DiffAdd", { bg = c.diff.add })
  hi("DiffChange", { bg = c.diff.change })
  hi("DiffDelete", { bg = c.diff.delete })
  hi("DiffText", { bg = c.diff.text })
  hi("Directory", { fg = c.blue })
  hi("EndOfBuffer", { fg = c.bg })
  hi("ErrorMsg", { fg = c.error })
  hi("FloatBorder", { fg = c.border_highlight, bg = opts.transparent and "NONE" or c.bg_float })
  hi("FloatTitle", { fg = c.fg, bg = opts.transparent and "NONE" or c.bg_float, bold = true })
  hi("FoldColumn", { fg = c.fg_gutter })
  hi("Folded", { fg = c.fg_dark, bg = c.bg_highlight })
  hi("IncSearch", { fg = c.bg, bg = c.yellow, bold = true })
  hi("LineNr", { fg = c.fg_gutter })
  hi("LineNrAbove", { fg = c.fg_gutter })
  hi("LineNrBelow", { fg = c.fg_gutter })
  hi("MatchParen", { fg = c.yellow, bold = true })
  hi("ModeMsg", { fg = c.fg_dark })
  hi("MoreMsg", { fg = c.blue })
  hi("MsgArea", { fg = c.fg })
  hi("MsgSeparator", { fg = c.border, bg = c.bg })
  hi("NonText", { fg = c.fg_gutter })
  hi("Normal", { fg = c.fg, bg = opts.transparent and "NONE" or c.bg })
  hi("NormalFloat", { fg = c.fg_float, bg = opts.transparent and "NONE" or c.bg_float })
  hi("NormalNC", { fg = c.fg, bg = opts.transparent and "NONE" or c.bg })
  hi("Pmenu", { fg = c.fg, bg = c.bg_popup })
  hi("PmenuExtra", { fg = c.fg_dark, bg = c.bg_popup })
  hi("PmenuExtraSel", { fg = c.fg, bg = c.bg_visual })
  hi("PmenuKind", { fg = c.blue })
  hi("PmenuKindSel", { fg = c.blue, bg = c.bg_visual })
  hi("PmenuSbar", { bg = c.bg_highlight })
  hi("PmenuSel", { fg = c.fg, bg = c.bg_visual })
  hi("PmenuThumb", { bg = c.fg_gutter })
  hi("Question", { fg = c.blue })
  hi("QuickFixLine", { bg = c.bg_visual, bold = true })
  hi("Search", { fg = c.bg, bg = c.yellow })
  hi("SignColumn", { fg = c.fg_gutter, bg = opts.transparent and "NONE" or c.bg })
  hi("SnippetTabstop", { bg = c.bg_highlight })
  hi("SpecialKey", { fg = c.fg_gutter })
  hi("SpellBad", { sp = c.error, undercurl = true })
  hi("SpellCap", { sp = c.warning, undercurl = true })
  hi("SpellLocal", { sp = c.info, undercurl = true })
  hi("SpellRare", { sp = c.hint, undercurl = true })
  hi("StatusLine", { fg = c.fg_dark, bg = c.bg_statusline })
  hi("StatusLineNC", { fg = c.fg_gutter, bg = c.bg_statusline })
  hi("Substitute", { fg = c.bg, bg = c.red })
  hi("TabLine", { fg = c.fg_dark, bg = c.bg_statusline })
  hi("TabLineFill", { bg = c.bg_statusline })
  hi("TabLineSel", { fg = c.fg, bg = c.bg, bold = true })
  hi("TermCursor", { fg = c.bg, bg = c.fg })
  hi("TermCursorNC", { fg = c.fg, bg = c.bg })
  hi("Title", { fg = c.blue, bold = true })
  hi("Visual", { bg = c.bg_visual })
  hi("VisualNOS", { bg = c.bg_visual })
  hi("WarningMsg", { fg = c.warning })
  hi("Whitespace", { fg = c.fg_gutter })
  hi("WildMenu", { fg = c.fg, bg = c.bg_visual })
  hi("WinBar", { fg = c.fg_dark, bg = opts.transparent and "NONE" or c.bg })
  hi("WinBarNC", { fg = c.fg_gutter, bg = opts.transparent and "NONE" or c.bg })
  hi("WinSeparator", { fg = c.border })
  hi("lCursor", { fg = c.bg, bg = c.fg })

  -- Syntax
  hi("Comment", { fg = c.comment, italic = opts.styles.comments.italic })
  hi("Constant", { fg = c.constant })
  hi("String", { fg = c.string })
  hi("Character", { fg = c.string })
  hi("Number", { fg = c.number })
  hi("Boolean", { fg = c.boolean })
  hi("Float", { fg = c.number })
  hi("Identifier", { fg = c.variable })
  hi("Function", { fg = c.func })
  hi("Statement", { fg = c.keyword })
  hi("Conditional", { fg = c.keyword })
  hi("Repeat", { fg = c.keyword })
  hi("Label", { fg = c.keyword })
  hi("Operator", { fg = c.operator })
  hi("Keyword", { fg = c.keyword, italic = opts.styles.keywords.italic })
  hi("Exception", { fg = c.keyword })
  hi("PreProc", { fg = c.keyword })
  hi("Include", { fg = c.keyword })
  hi("Define", { fg = c.keyword })
  hi("Macro", { fg = c.keyword })
  hi("PreCondit", { fg = c.keyword })
  hi("Type", { fg = c.type })
  hi("StorageClass", { fg = c.type })
  hi("Structure", { fg = c.type })
  hi("Typedef", { fg = c.type })
  hi("Special", { fg = c.builtin })
  hi("SpecialChar", { fg = c.builtin })
  hi("Tag", { fg = c.keyword })
  hi("Delimiter", { fg = c.punctuation })
  hi("SpecialComment", { fg = c.comment, italic = true })
  hi("Debug", { fg = c.orange })
  hi("Underlined", { underline = true })
  hi("Ignore", { fg = c.fg_gutter })
  hi("Error", { fg = c.error })
  hi("Todo", { fg = c.todo, bold = true })

  -- Treesitter
  hi("@attribute", { fg = c.decorator })
  hi("@attribute.builtin", { fg = c.decorator })
  hi("@boolean", { fg = c.boolean })
  hi("@character", { fg = c.string })
  hi("@character.special", { fg = c.builtin })
  hi("@comment", { fg = c.comment, italic = opts.styles.comments.italic })
  hi("@comment.error", { fg = c.error, bold = true })
  hi("@comment.note", { fg = c.note, bold = true })
  hi("@comment.todo", { fg = c.todo, bold = true })
  hi("@comment.warning", { fg = c.warning, bold = true })
  hi("@conditional", { fg = c.keyword })
  hi("@constant", { fg = c.constant })
  hi("@constant.builtin", { fg = c.constant })
  hi("@constant.macro", { fg = c.constant })
  hi("@constructor", { fg = c.class })
  hi("@debug", { fg = c.orange })
  hi("@define", { fg = c.keyword })
  hi("@error", { fg = c.error })
  hi("@exception", { fg = c.keyword })
  hi("@field", { fg = c.property })
  hi("@float", { fg = c.number })
  hi("@function", { fg = c.func })
  hi("@function.builtin", { fg = c.builtin })
  hi("@function.call", { fg = c.func })
  hi("@function.macro", { fg = c.func })
  hi("@function.method", { fg = c.func })
  hi("@function.method.call", { fg = c.func })
  hi("@include", { fg = c.keyword })
  hi("@keyword", { fg = c.keyword, italic = opts.styles.keywords.italic })
  hi("@keyword.conditional", { fg = c.keyword })
  hi("@keyword.coroutine", { fg = c.keyword })
  hi("@keyword.debug", { fg = c.keyword })
  hi("@keyword.directive", { fg = c.keyword })
  hi("@keyword.directive.define", { fg = c.keyword })
  hi("@keyword.exception", { fg = c.keyword })
  hi("@keyword.function", { fg = c.keyword, italic = opts.styles.keywords.italic })
  hi("@keyword.import", { fg = c.keyword })
  hi("@keyword.modifier", { fg = c.keyword })
  hi("@keyword.operator", { fg = c.operator })
  hi("@keyword.repeat", { fg = c.keyword })
  hi("@keyword.return", { fg = c.keyword })
  hi("@keyword.type", { fg = c.type })
  hi("@label", { fg = c.keyword })
  hi("@markup", { fg = c.fg })
  hi("@markup.heading", { fg = c.green, bold = true })
  hi("@markup.italic", { italic = true })
  hi("@markup.link", { fg = c.blue })
  hi("@markup.link.label", { fg = c.blue })
  hi("@markup.link.url", { fg = c.blue, underline = true })
  hi("@markup.list", { fg = c.orange })
  hi("@markup.literal", { fg = c.string })
  hi("@markup.strong", { bold = true })
  hi("@module", { fg = c.namespace })
  hi("@module.builtin", { fg = c.namespace })
  hi("@namespace", { fg = c.namespace })
  hi("@namespace.builtin", { fg = c.namespace })
  hi("@number", { fg = c.number })
  hi("@number.float", { fg = c.number })
  hi("@operator", { fg = c.operator })
  hi("@property", { fg = c.property })
  hi("@property.builtin", { fg = c.property })
  hi("@punctuation", { fg = c.punctuation })
  hi("@punctuation.bracket", { fg = c.punctuation })
  hi("@punctuation.delimiter", { fg = c.punctuation })
  hi("@punctuation.special", { fg = c.punctuation })
  hi("@repeat", { fg = c.keyword })
  hi("@string", { fg = c.string })
  hi("@string.documentation", { fg = c.comment })
  hi("@string.escape", { fg = c.yellow })
  hi("@string.regexp", { fg = c.regex })
  hi("@string.special", { fg = c.builtin })
  hi("@string.special.symbol", { fg = c.constant })
  hi("@string.special.url", { fg = c.blue, underline = true })
  hi("@tag", { fg = c.keyword })
  hi("@tag.attribute", { fg = c.property })
  hi("@tag.builtin", { fg = c.keyword })
  hi("@tag.delimiter", { fg = c.punctuation })
  hi("@type", { fg = c.type })
  hi("@type.builtin", { fg = c.type })
  hi("@type.definition", { fg = c.type })
  hi("@variable", { fg = c.variable })
  hi("@variable.builtin", { fg = c.builtin })
  hi("@variable.member", { fg = c.property })
  hi("@variable.parameter", { fg = c.fg })
  hi("@variable.parameter.builtin", { fg = c.fg_dark })

  -- LSP semantic tokens
  hi("@lsp.type.class", { fg = c.class })
  hi("@lsp.type.comment", { fg = c.comment, italic = opts.styles.comments.italic })
  hi("@lsp.type.decorator", { fg = c.decorator })
  hi("@lsp.type.enum", { fg = c.type })
  hi("@lsp.type.enumMember", { fg = c.constant })
  hi("@lsp.type.event", { fg = c.type })
  hi("@lsp.type.function", { fg = c.func })
  hi("@lsp.type.interface", { fg = c.interface })
  hi("@lsp.type.keyword", { fg = c.keyword, italic = opts.styles.keywords.italic })
  hi("@lsp.type.macro", { fg = c.func })
  hi("@lsp.type.method", { fg = c.func })
  hi("@lsp.type.modifier", { fg = c.keyword })
  hi("@lsp.type.namespace", { fg = c.namespace })
  hi("@lsp.type.number", { fg = c.number })
  hi("@lsp.type.operator", { fg = c.operator })
  hi("@lsp.type.parameter", { fg = c.fg })
  hi("@lsp.type.property", { fg = c.property })
  hi("@lsp.type.regexp", { fg = c.regex })
  hi("@lsp.type.string", { fg = c.string })
  hi("@lsp.type.struct", { fg = c.type })
  hi("@lsp.type.type", { fg = c.type })
  hi("@lsp.type.typeParameter", { fg = c.type })
  hi("@lsp.type.variable", { fg = c.variable })
  hi("@lsp.mod.deprecated", { strikethrough = true })

  -- Diagnostics
  hi("DiagnosticError", { fg = c.error })
  hi("DiagnosticWarn", { fg = c.warning })
  hi("DiagnosticInfo", { fg = c.info })
  hi("DiagnosticHint", { fg = c.hint })
  hi("DiagnosticOk", { fg = c.green })
  hi("DiagnosticVirtualTextError", { fg = c.error, bg = c.diff.delete })
  hi("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.diff.change })
  hi("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.diff.change })
  hi("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.diff.change })
  hi("DiagnosticVirtualTextOk", { fg = c.green, bg = c.diff.add })
  hi("DiagnosticUnderlineError", { sp = c.error, underline = true })
  hi("DiagnosticUnderlineWarn", { sp = c.warning, underline = true })
  hi("DiagnosticUnderlineInfo", { sp = c.info, underline = true })
  hi("DiagnosticUnderlineHint", { sp = c.hint, underline = true })
  hi("DiagnosticUnderlineOk", { sp = c.green, underline = true })
  hi("DiagnosticSignError", { fg = c.error })
  hi("DiagnosticSignWarn", { fg = c.warning })
  hi("DiagnosticSignInfo", { fg = c.info })
  hi("DiagnosticSignHint", { fg = c.hint })
  hi("DiagnosticSignOk", { fg = c.green })
  hi("DiagnosticFloatingError", { fg = c.error })
  hi("DiagnosticFloatingWarn", { fg = c.warning })
  hi("DiagnosticFloatingInfo", { fg = c.info })
  hi("DiagnosticFloatingHint", { fg = c.hint })
  hi("DiagnosticFloatingOk", { fg = c.green })

  -- Git
  hi("gitHash", { fg = c.fg_dark })
  hi("gitcommitArrow", { fg = c.fg_dark })
  hi("gitcommitDiscarded", { fg = c.red })
  hi("gitcommitDiscardedArrow", { fg = c.red })
  hi("gitcommitOverflow", { fg = c.red })
  hi("gitcommitSelected", { fg = c.green })
  hi("gitcommitSelectedArrow", { fg = c.green })
  hi("gitcommitSummary", { fg = c.fg })
  hi("gitcommitUnmerged", { fg = c.green })
  hi("gitcommitUnmergedArrow", { fg = c.green })
  hi("gitcommitUntracked", { fg = c.blue })
  hi("gitcommitUntrackedArrow", { fg = c.blue })

  hi("DiffAdded", { fg = c.git.add, bg = c.diff.add })
  hi("DiffRemoved", { fg = c.git.delete, bg = c.diff.delete })
  hi("DiffChanged", { fg = c.git.change, bg = c.diff.change })
  hi("DiffOldFile", { fg = c.yellow })
  hi("DiffNewFile", { fg = c.orange })
  hi("DiffFile", { fg = c.blue })
  hi("DiffLine", { fg = c.fg_gutter })
  hi("DiffIndexLine", { fg = c.magenta })

  -- Gitsigns
  hi("GitSignsAdd", { fg = c.git.add })
  hi("GitSignsChange", { fg = c.git.change })
  hi("GitSignsDelete", { fg = c.git.delete })
  hi("GitSignsAddInline", { bg = c.diff.add })
  hi("GitSignsChangeInline", { bg = c.diff.change })
  hi("GitSignsDeleteInline", { bg = c.diff.delete })
  hi("GitSignsAddLnInline", { bg = c.diff.add })
  hi("GitSignsChangeLnInline", { bg = c.diff.change })
  hi("GitSignsDeleteLnInline", { bg = c.diff.delete })

  -- Telescope
  hi("TelescopeBorder", { fg = c.border_highlight, bg = c.bg_float })
  hi("TelescopeNormal", { fg = c.fg, bg = c.bg_float })
  hi("TelescopePromptBorder", { fg = c.border_highlight, bg = c.bg_float })
  hi("TelescopePromptNormal", { fg = c.fg, bg = c.bg_float })
  hi("TelescopePromptPrefix", { fg = c.blue })
  hi("TelescopePromptTitle", { fg = c.bg, bg = c.blue, bold = true })
  hi("TelescopePreviewTitle", { fg = c.bg, bg = c.green, bold = true })
  hi("TelescopeResultsTitle", { fg = c.bg, bg = c.blue, bold = true })
  hi("TelescopeSelection", { fg = c.fg, bg = c.bg_visual })
  hi("TelescopeSelectionCaret", { fg = c.blue })
  hi("TelescopeMatching", { fg = c.yellow, bold = true })

  -- Neo-tree
  hi("NeoTreeDirectoryIcon", { fg = c.blue })
  hi("NeoTreeDirectoryName", { fg = c.blue })
  hi("NeoTreeFileName", { fg = c.fg })
  hi("NeoTreeFileNameOpened", { fg = c.fg, bold = true })
  hi("NeoTreeGitAdded", { fg = c.git.add })
  hi("NeoTreeGitConflict", { fg = c.red })
  hi("NeoTreeGitDeleted", { fg = c.git.delete })
  hi("NeoTreeGitIgnored", { fg = c.git.ignore })
  hi("NeoTreeGitModified", { fg = c.git.change })
  hi("NeoTreeGitUnstaged", { fg = c.git.change })
  hi("NeoTreeGitUntracked", { fg = c.blue })
  hi("NeoTreeGitStaged", { fg = c.git.add })
  hi("NeoTreeIndentMarker", { fg = c.fg_gutter })
  hi("NeoTreeNormal", { fg = c.fg, bg = c.bg })
  hi("NeoTreeNormalNC", { fg = c.fg, bg = c.bg })
  hi("NeoTreeRootName", { fg = c.blue, bold = true })
  hi("NeoTreeSymbolicLinkTarget", { fg = c.magenta })

  -- NvimTree
  hi("NvimTreeFolderIcon", { fg = c.blue })
  hi("NvimTreeFolderName", { fg = c.blue })
  hi("NvimTreeGitDeleted", { fg = c.git.delete })
  hi("NvimTreeGitDirty", { fg = c.git.change })
  hi("NvimTreeGitNew", { fg = c.git.add })
  hi("NvimTreeIndentMarker", { fg = c.fg_gutter })
  hi("NvimTreeNormal", { fg = c.fg, bg = c.bg })
  hi("NvimTreeOpenedFolderName", { fg = c.blue, bold = true })
  hi("NvimTreeRootFolder", { fg = c.blue, bold = true })
  hi("NvimTreeSpecialFile", { fg = c.magenta, underline = true })

  -- WhichKey
  hi("WhichKey", { fg = c.fg })
  hi("WhichKeyGroup", { fg = c.blue })
  hi("WhichKeySeparator", { fg = c.fg_gutter })
  hi("WhichKeyDesc", { fg = c.green })
  hi("WhichKeyValue", { fg = c.fg_dark })

  -- Lazy
  hi("LazyButton", { bg = c.bg_highlight })
  hi("LazyButtonActive", { fg = c.bg, bg = c.green, bold = true })
  hi("LazyComment", { fg = c.comment })
  hi("LazyCommit", { fg = c.green })
  hi("LazyCommitIssue", { fg = c.magenta })
  hi("LazyCommitType", { fg = c.yellow })
  hi("LazyDir", { fg = c.blue })
  hi("LazyH1", { fg = c.bg, bg = c.blue, bold = true })
  hi("LazyProgressDone", { fg = c.green })
  hi("LazyProgressTodo", { fg = c.fg_gutter })
  hi("LazyProp", { fg = c.yellow })
  hi("LazyReasonCmd", { fg = c.blue })
  hi("LazyReasonEvent", { fg = c.yellow })
  hi("LazyReasonFt", { fg = c.cyan })
  hi("LazyReasonImport", { fg = c.magenta })
  hi("LazyReasonKeys", { fg = c.green })
  hi("LazyReasonPlugin", { fg = c.orange })
  hi("LazyReasonRuntime", { fg = c.blue })
  hi("LazyReasonSource", { fg = c.cyan })
  hi("LazyReasonStart", { fg = c.green })
  hi("LazySpecial", { fg = c.blue })
  hi("LazyTaskError", { fg = c.error })
  hi("LazyTaskOutput", { fg = c.fg_dark })
  hi("LazyUrl", { fg = c.blue, underline = true })
  hi("LazyValue", { fg = c.orange })

  -- Mason
  hi("MasonNormal", { fg = c.fg, bg = c.bg_float })
  hi("MasonHeader", { fg = c.bg, bg = c.blue, bold = true })
  hi("MasonHeaderSecondary", { fg = c.bg, bg = c.green, bold = true })
  hi("MasonHighlight", { fg = c.green })
  hi("MasonHighlightBlock", { fg = c.bg, bg = c.green })
  hi("MasonHighlightBlockBold", { fg = c.bg, bg = c.green, bold = true })
  hi("MasonHighlightSecondary", { fg = c.yellow })
  hi("MasonHighlightBlockSecondary", { fg = c.bg, bg = c.yellow })
  hi("MasonHighlightBlockBoldSecondary", { fg = c.bg, bg = c.yellow, bold = true })
  hi("MasonMuted", { fg = c.fg_gutter })
  hi("MasonMutedBlock", { fg = c.fg, bg = c.bg_highlight })

  -- CMP
  hi("CmpItemAbbr", { fg = c.fg })
  hi("CmpItemAbbrDeprecated", { fg = c.fg_gutter, strikethrough = true })
  hi("CmpItemAbbrMatch", { fg = c.blue, bold = true })
  hi("CmpItemAbbrMatchFuzzy", { fg = c.blue, bold = true })
  hi("CmpItemKind", { fg = c.fg_dark })
  hi("CmpItemMenu", { fg = c.fg_dark })
  hi("CmpItemKindClass", { fg = c.class })
  hi("CmpItemKindColor", { fg = c.fg })
  hi("CmpItemKindConstant", { fg = c.constant })
  hi("CmpItemKindConstructor", { fg = c.class })
  hi("CmpItemKindEnum", { fg = c.type })
  hi("CmpItemKindEnumMember", { fg = c.constant })
  hi("CmpItemKindEvent", { fg = c.type })
  hi("CmpItemKindField", { fg = c.property })
  hi("CmpItemKindFile", { fg = c.blue })
  hi("CmpItemKindFolder", { fg = c.blue })
  hi("CmpItemKindFunction", { fg = c.func })
  hi("CmpItemKindInterface", { fg = c.interface })
  hi("CmpItemKindKeyword", { fg = c.keyword })
  hi("CmpItemKindMethod", { fg = c.func })
  hi("CmpItemKindModule", { fg = c.namespace })
  hi("CmpItemKindOperator", { fg = c.operator })
  hi("CmpItemKindProperty", { fg = c.property })
  hi("CmpItemKindReference", { fg = c.variable })
  hi("CmpItemKindSnippet", { fg = c.yellow })
  hi("CmpItemKindStruct", { fg = c.type })
  hi("CmpItemKindText", { fg = c.fg })
  hi("CmpItemKindTypeParameter", { fg = c.type })
  hi("CmpItemKindUnit", { fg = c.orange })
  hi("CmpItemKindValue", { fg = c.constant })
  hi("CmpItemKindVariable", { fg = c.variable })

  -- Indent Blankline
  hi("IblIndent", { fg = c.fg_gutter })
  hi("IblScope", { fg = c.border_highlight })
  hi("IblWhitespace", { fg = c.fg_gutter })

  -- Snacks
  hi("SnacksNormal", { fg = c.fg, bg = c.bg_float })
  hi("SnacksBorder", { fg = c.border_highlight, bg = c.bg_float })
  hi("SnacksTitle", { fg = c.fg, bg = c.bg_float, bold = true })
  hi("SnacksPrompt", { fg = c.blue })
  hi("SnacksNotifierError", { fg = c.error })
  hi("SnacksNotifierWarn", { fg = c.warning })
  hi("SnacksNotifierInfo", { fg = c.info })
  hi("SnacksNotifierDebug", { fg = c.fg_dark })
  hi("SnacksNotifierTrace", { fg = c.hint })
  hi("SnacksNotifierTitleError", { fg = c.error, bold = true })
  hi("SnacksNotifierTitleWarn", { fg = c.warning, bold = true })
  hi("SnacksNotifierTitleInfo", { fg = c.info, bold = true })
  hi("SnacksNotifierTitleDebug", { fg = c.fg_dark, bold = true })
  hi("SnacksNotifierTitleTrace", { fg = c.hint, bold = true })

  -- Markdown/render-markdown
  hi("RenderMarkdownH1Bg", { bg = c.diff.add })
  hi("RenderMarkdownH2Bg", { bg = c.diff.change })
  hi("RenderMarkdownH3Bg", { bg = c.diff.change })
  hi("RenderMarkdownH4Bg", { bg = c.diff.change })
  hi("RenderMarkdownH5Bg", { bg = c.diff.change })
  hi("RenderMarkdownH6Bg", { bg = c.diff.change })
  hi("RenderMarkdownCode", { bg = c.bg_highlight })
  hi("RenderMarkdownCodeInline", { bg = c.bg_highlight })
  hi("RenderMarkdownBullet", { fg = c.orange })
  hi("RenderMarkdownTableHead", { fg = c.blue, bold = true })
  hi("RenderMarkdownTableRow", { fg = c.fg })

  -- Statusline / bufferline (generic)
  hi("StatusLineAccent", { fg = c.bg, bg = c.green, bold = true })
  hi("BufferLineFill", { bg = c.bg_statusline })
  hi("BufferLineSeparator", { fg = c.border })

  return hl
end

return M
