# Herdr theme: Vitesse Dark
# Source: https://github.com/antfu/vscode-theme-vitesse

[theme]
name = "catppuccin"

[theme.custom]
panel_bg = "#121212"
text = "#dbd7ca"
subtext0 = "#bfbaaa"
surface0 = "#181818"
surface1 = "#181818"
surface_dim = "#1b2e25"
accent = "#4d9375"
green = "#4d9375"
blue = "#6394bf"
red = "#cb7676"
yellow = "#e6cc77"
