# Herdr theme: Vitesse Dark Soft
# Source: https://github.com/antfu/vscode-theme-vitesse

[theme]
name = "catppuccin"

[theme.custom]
panel_bg = "#222222"
text = "#dbd7ca"
subtext0 = "#bfbaaa"
surface0 = "#292929"
surface1 = "#292929"
surface_dim = "#25332b"
accent = "#4d9375"
green = "#4d9375"
blue = "#6394bf"
red = "#cb7676"
yellow = "#e6cc77"
