# Herdr theme: Vitesse Light Soft
# Source: https://github.com/antfu/vscode-theme-vitesse

[theme]
name = "catppuccin"

[theme.custom]
panel_bg = "#F1F0E9"
text = "#393a34"
subtext0 = "#4e4f47"
surface0 = "#E7E5DB"
surface1 = "#E7E5DB"
surface_dim = "#dbe5df"
accent = "#1c6b48"
green = "#1e754f"
blue = "#296aa3"
red = "#ab5959"
yellow = "#bda437"
