# Herdr theme: Vitesse Light
# Source: https://github.com/antfu/vscode-theme-vitesse

[theme]
name = "catppuccin"

[theme.custom]
panel_bg = "#ffffff"
text = "#393a34"
subtext0 = "#4e4f47"
surface0 = "#f7f7f7"
surface1 = "#f7f7f7"
surface_dim = "#e1ebe5"
accent = "#1c6b48"
green = "#1e754f"
blue = "#296aa3"
red = "#ab5959"
yellow = "#bda437"
