# vim:ft=kitty
## name: Vitesse Light
## author: Anthony Fu
## license: MIT
## upstream: https://github.com/antfu/vscode-theme-vitesse
## blurb: A soft, low-contrast light theme inspired by the Vitesse palette

foreground                      #393a34
background                      #ffffff
selection_foreground            #393a34
selection_background            #eaeaea

cursor                          #393a34
cursor_text_color               #ffffff

url_color                       #1c6b48

active_border_color             #1c6b48
inactive_border_color           #999999
bell_border_color               #ab5959
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #ffffff
active_tab_foreground           #393a34
inactive_tab_background         #f7f7f7
inactive_tab_foreground         #999999
tab_bar_background              #f7f7f7
tab_bar_margin_color            none

mark1_foreground                #ffffff
mark1_background                #296aa3
mark2_foreground                #ffffff
mark2_background                #1e754f
mark3_foreground                #ffffff
mark3_background                #a13865

#: black
color0                          #ffffff
color8                          #aaaaaa

#: red
color1                          #ab5959
color9                          #ab5959

#: green
color2                          #1e754f
color10                         #1e754f

#: yellow
color3                          #bda437
color11                         #bda437

#: blue
color4                          #296aa3
color12                         #296aa3

#: magenta
color5                          #a13865
color13                         #a13865

#: cyan
color6                          #2993a3
color14                         #2993a3

#: white
color7                          #393a34
color15                         #dddddd
