# vim:ft=kitty
## name: Vitesse Dark Soft
## author: Anthony Fu
## license: MIT
## upstream: https://github.com/antfu/vscode-theme-vitesse
## blurb: A softer dark variant of the Vitesse palette

foreground                      #dbd7ca
background                      #222222
selection_foreground            #dbd7ca
selection_background            #303030

cursor                          #dbd7ca
cursor_text_color               #222222

url_color                       #4d9375

active_border_color             #4d9375
inactive_border_color           #666666
bell_border_color               #cb7676
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #222222
active_tab_foreground           #dbd7ca
inactive_tab_background         #292929
inactive_tab_foreground         #777777
tab_bar_background              #292929
tab_bar_margin_color            none

mark1_foreground                #222222
mark1_background                #6394bf
mark2_foreground                #222222
mark2_background                #4d9375
mark3_foreground                #222222
mark3_background                #d9739f

#: black
color0                          #222222
color8                          #777777

#: red
color1                          #cb7676
color9                          #cb7676

#: green
color2                          #4d9375
color10                         #4d9375

#: yellow
color3                          #e6cc77
color11                         #e6cc77

#: blue
color4                          #6394bf
color12                         #6394bf

#: magenta
color5                          #d9739f
color13                         #d9739f

#: cyan
color6                          #5eaab5
color14                         #5eaab5

#: white
color7                          #dbd7ca
color15                         #ffffff
